### ISSUE TITLE
Use export in .example.env file

### ISSUE THREAD

**Issue by Rishabh570** [smallcase/url-shortener#8]
Hey there! Happy to see you here 😃. This is a `first-timers only` issue. It is specifically for people who want to get started with open source and want to contribute to smalllinks.

If you have already contributed to smalllinks or have some experience with open source software, we would request you to work on some other issue. Or better yet, create an issue for newcomers!

## ☑️ Step-by-step breakdown of how you can contribute to resolving this issue:

1. Claim this issue by leaving a comment. This way, anyone who lands on this issue would know the status. If it is already claimed by someone, you can ask them about the status and even collaborate with them.

2. (Optional) If you haven't set up the project locally, follow [these steps](https://github.com/smallcase/smalllinks/blob/development/README.md#installation) first.

3. Create a new branch

4. Below is the DIFF of the code changes that are required:

- `.example.env`

```diff
- APPLICATION_NAME=smalllinks
- BASE_URL='localhost:8201'
- PORT=8201
- SHORTENER_DEBUG='true'
- SHORT_URL_LENGTH=5
- SHORT_KEY_GENERATION_RETRIES_COUNT=5
- KAFKA_HOST='localhost:9092' # 'kafka:9092' for docker-compose
- LOG_LEVEL=info
- DB_USER=postgres
- DB_HOST=localhost # 'mypostgresdb'  for docker-compose
- DB_NAME=fastdb
- DB_PASSWORD=postgres
- DB_PORT=5432
- DB_CONNECTIONS=10
- DB_IDLE_TIMEOUT=5000
- DB_CONNECTION_TIMEOUT=60000
- shortenedLinksTable=shortenedLinks
- shortUrlExpiryTable=shortUrlExpiry
- REDIS_HOST=localhost # 'redis' for docker-compose
- REDIS_PORT=6379
- POSTGRES_USER="postgres"
- POSTGRES_PASSWORD="postgres"
- POSTGRES_DB="fastdb"
- KAFKA_CREATE_TOPICS='shortUrlOpened'
- KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
- KAFKA_ADVERTISED_HOST_NAME=host.docker.internal # change to 172.17.0.1 if running on Ubuntu

+ export APPLICATION_NAME=smalllinks
+ export BASE_URL='localhost:8201'
+ export PORT=8201
+ export SHORTENER_DEBUG='true'
+ export SHORT_URL_LENGTH=5
+ export SHORT_KEY_GENERATION_RETRIES_COUNT=5
+ export KAFKA_HOST='localhost:9092' # 'kafka:9092' for docker-compose
+ export LOG_LEVEL=info
+ export DB_USER=postgres
+ export DB_HOST=localhost # 'mypostgresdb'  for docker-compose
+ export DB_NAME=fastdb
+ export DB_PASSWORD=postgres
+ export DB_PORT=5432
+ export DB_CONNECTIONS=10
+ export DB_IDLE_TIMEOUT=5000
+ export DB_CONNECTION_TIMEOUT=60000
+ export shortenedLinksTable=shortenedLinks
+ export shortUrlExpiryTable=shortUrlExpiry
+ export REDIS_HOST=localhost # 'redis' for docker-compose
+ export REDIS_PORT=6379

+ export POSTGRES_USER="postgres"
+ export POSTGRES_PASSWORD="postgres"
+ export POSTGRES_DB="fastdb"

+ export KAFKA_CREATE_TOPICS='shortUrlOpened'
+ export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
+ export KAFKA_ADVERTISED_HOST_NAME=host.docker.internal # change to 172.17.0.1 if running on Ubuntu
```

5. Commit your changes

6. Raise a PR 🙌

## 🎐 Some resources that might help in the process:

- [How to contribute to an open-source project on github](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github)
- [Editing files on Github](https://docs.github.com/en/github/managing-files-in-a-repository/managing-files-on-github/editing-files-in-another-users-repository)

---

If you have any questions, please drop a comment below and we'll be happy to connect!

**Comment by ryandorrington** [comment]
Hey Rishabh570, I would be happy to lend a helping hand.
